site:
  name: Unified Networks
  site: 'https://unifiednetworks.ie'
  base: '/'
  trailingSlash: false
  googleSiteVerificationId: null

metadata:
  title:
    default: Unified Networks
    template: '%s | Unified Networks'
  description: 'Network setup, Wi-Fi optimization, Starlink installation, and internet troubleshooting across Louth, Meath, Dublin, Kildare, Wicklow, Cavan, Monaghan, Westmeath, and Laois.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Unified Networks
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: null
    site: null
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%'
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: true

    isRelatedPostsEnabled: true
    relatedPostsCount: 3

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'system'
