site:
  name: Unified Networks
  site: 'https://unifiednetworks.ie'
  base: '/'
  trailingSlash: false
  googleSiteVerificationId: null

metadata:
  title:
    default: Unified Networks
    template: '%s | Unified Networks'
  description: 'Network setup, Wi-Fi optimization, Starlink installation, and internet troubleshooting for homes and businesses.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Unified Networks
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: null
    site: null
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6
    post:
      isEnabled: false
      permalink: '/%slug%'
      robots:
        index: false
    list:
      isEnabled: false
      pathname: 'blog'
      robots:
        index: false
    category:
      isEnabled: false
      pathname: 'category'
      robots:
        index: false
    tag:
      isEnabled: false
      pathname: 'tag'
      robots:
        index: false
    isRelatedPostsEnabled: false
    relatedPostsCount: 0

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'system'
